version: '3'
services:
  app:
    image: node:16
    working_dir: /usr/src/app
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    command: >
        bash -c "npm install && npm install nodemon -g && nodemon index.js"

  db:
    image: postgres:15
    expose:
      - "5432"
    volumes:
      - ./docker/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
